server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hello?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379



mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lirt.springboot.entity
#    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com:
      lirt:
        springboot:
          mapper: debug

